export const FETCHING_SMURFS_START = 'FETCHING_SMURFS_START'
export const FETCHING_SMURFS_SUCCESS = 'FETCHING_SMURFS_SUCCESS'
export const FETCHING_SMURFS_ERROR = 'FETCHING_SMURF_ERROR'

export const SUBMIT_SMURF_START = 'SUBMIT_SMURF_START'
export const SUBMIT_SMURF_SUCCESS = 'SUBMIT_SMURF_SUCCESS'
export const SUBMIT_SMURF_ERROR = 'SUBMIT_SMURF_ERROR'